### ISSUE TITLE
Updating Aucor Core to 1.1 disables the plugin.

### ISSUE THREAD

**Issue by Jaska** [aucor/aucor-core#16]
Tested with ManageWP remote updating and updating with /wp-admin/update-core.php
Plugins page has error message:
"Lisäosa aucor-core/plugin.php on poistettu käytöstä, koska se aiheutti virhetilanteen: Lisäosan tiedostoa ei ole olemassa."

Themes usually depend on this plugin so this breaks some site features. 
The fix is obviously just activating the plugin.

**Comment by Jntz** [comment]
Yes I got same problem! Thanks Jaska for tell how to fix this problem. I just started wonder why localization not work in our websites.

**Comment by TeemuSuoranta** [comment]
Thanks for letting us know! We just moved the WP.org workflow to Github actions and even though we do have automated testing, something went weirdly wrong.

**Comment by TeemuSuoranta** [comment]
Seems like the plugin main file used to be `plugin.php` and it was changed to `aucor-core.php` and updated doesn't like that.

I'll try a "hotfix" as a `plugin.php` that just requires the `aucor-core.php` so even if the WP tries to include the old file, everything still works.

**Comment by TeemuSuoranta** [comment]
Version 1.1.3 is now released that fixes the issue. WP-CLI command `wp plugin list` now lists plugin twice as there needs to be two working "plugin root files" to avoid this issue to new and old installations.

Let that be a lesson never to rename plugin root file.
